scene.onHitWall(SpriteKind.Food, function (sprite, location) {
    sprite.destroy(effects.clouds, 100)
    info.changeLifeBy(-1)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (sprite, otherSprite) {
    info.changeScoreBy(1)
    otherSprite.destroy(effects.fire, 200)
    if (info.score() == 50) {
        game.over(true)
    }
})
let Burger: Sprite = null
game.splash("hojigdwol suga", "51 onoo awbal shagnaltai")
tiles.setCurrentTilemap(tilemap`level1`)
let Metaman = sprites.create(img`
    . . . . f f f f . . . . . 
    . . f f c c c c f f . . . 
    . f f c c c c c c f f . . 
    f f c c c c c c c c f f . 
    f f c c f c c c c c c f . 
    f f f f f c c c f c c f . 
    f f f f c c c f c c f f . 
    f f f f f f f f f f f f . 
    f f f f f f f f f f f f . 
    . f f f f f f f f f f . . 
    . f f f f f f f f f f . . 
    f e f f f f f f f f e f . 
    e 4 f 7 7 7 7 7 7 c 4 e . 
    e e f 6 6 6 6 6 6 f e e . 
    . . . f f f f f f . . . . 
    . . . f f . . f f . . . . 
    `, SpriteKind.Player)
controller.moveSprite(Metaman, 100, 0)
Metaman.setPosition(80, 105)
info.setScore(-50)
info.setLife(3)
game.onUpdateInterval(1000, function () {
    Burger = sprites.create(img`
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        .......22...22......
        ......2322.2222.....
        ......232222222.....
        ......222222222.....
        .......22222b2......
        ........222b2.......
        .........222........
        ..........2.........
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        `, SpriteKind.Food)
    Burger.setPosition(randint(0, 160), 0)
    Burger.setVelocity(0, 15)
})
